apiVersion: v1
kind: Service
metadata:
  name: nginx
  labels:
    app.kubernetes.io/instance: nginx
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/instance: nginx-dp
---

# Source: popoint-essential/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-dp
  labels:
    app.kubernetes.io/instance: nginx-dp
spec:
  replicas: 2
  selector:
    matchLabels:
      app.kubernetes.io/instance: nginx-dp
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: nginx-dp
    spec:
      containers:
        - name: nginx-nginx
          image: "nginx:alpine"
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 80
              protocol: TCP            
          resources:
            limits:
              cpu: "0.3"
              memory: 256Mi
            requests:
              cpu: "0.01"
              memory: 128Mi
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: nginx-dp-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: nginx-dp
  minReplicas: 1
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50
---
# Source: popoint-essential/templates/deployment.yaml
# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: nginx-dp2
#   labels:
#     app.kubernetes.io/instance: nginx-dp2
# spec:
#   replicas: 2
#   selector:
#     matchLabels:
#       app.kubernetes.io/instance: nginx-dp2
#   template:
#     metadata:
#       labels:
#         app.kubernetes.io/instance: nginx-dp2
#     spec:
#       containers:
#         - name: nginx-nginx
#           image: "nginx:alpine"
#           imagePullPolicy: IfNotPresent
#           ports:
#             - name: http
#               containerPort: 80
#               protocol: TCP            
#           resources:
#             limits:
#               cpu: "0.3"
#               memory: 256Mi
#             requests:
#               cpu: "0.01"
#               memory: 128Mi              