namespace: prod
commonLabels:
  environment: prod
  kustomization: enabled
nameSuffix:
  -prod
images:
- name: nginx
  newTag: alpine
resources:
- deploy.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
